### ISSUE TITLE
Scrollback module can violate causality

### ISSUE THREAD

**Issue by euank** [euank/EuIrcBot#131] opened 2016-12-10 21:59 UTC
```
<ek> 2010-2016
<^> -6
```

Scrollback module sees:
```
<^> -6
<ek> 2010-2016
```

This is obviously a violation of the space-time continuum and should be fixed quickly

**Comment by LinuxMercedes** [comment] 2016-12-12 22:01
Closing #124 as a duplicate of this (via causality violation).

**Comment by brhoades** [comment] 2016-12-13 17:01
This appears to occur on any module which uses all messages to respond to input, rather than commands. So this affects regex too.

**Comment by brhoades** [comment] 2016-12-13 17:12
scrollback catches all messages dispatched from bot.js through the 'chan*' hook.
onMath catches all messages from bot.js through the 'msg' hook.

'msg' is always evaluated first in bot.js.

```javascript
 bot.client.on('message', function(from, to, text, raw) {
    var primaryFrom = (to == bot.client.nick) ? from : to;
    bot.callModuleFn('message', [text, from, to, bot.getReply(primaryFrom), raw]);

    bot.callModuleFn('msg', [text, from, bot.getReply(primaryFrom), raw]);

    if(to == bot.client.nick) {
      bot.callModuleFn('pm', [text, from, bot.getReply(from), raw]);
    } else {
      bot.callModuleFn('chanmsg', [text, to, from, bot.getReply(to), raw]);
    }
    // ....
  });
```

Flipping message/msg to be evaluated last works around this... but we need a fix. Suggestions?

**Comment by brhoades** [comment] 2016-12-14 14:15
👍

**Closed** 2017-03-10 17:36 UTC
